from datetime import datetime

from src import db
from src.__Parents.Model import Model


class OrderBookPatternStrategyConfig(Model, db.Model):
    __tablename__ = "order_book_pattern_strategy_config"

    exchange = db.Column(db.String(80), default="binance", nullable=False)
    symbol = db.Column(db.String(40), default="BTC/USDT", nullable=False)
    exchange_id = db.Column(db.Integer, db.ForeignKey("exchange.id"), nullable=True)
    trading_pair_id = db.Column(db.Integer, db.ForeignKey("trading_pair.id"), nullable=True)
    base_margin_usdt = db.Column(db.Float, default=7, nullable=False)
    leverage = db.Column(db.Float, default=2, nullable=False)
    max_recovery_steps = db.Column(db.Integer, default=2, nullable=False)
    recovery_multiplier = db.Column(db.Float, default=2, nullable=False)
    take_profit_percent_of_margin = db.Column(db.Float, default=10, nullable=False)
    stop_loss_percent_of_margin = db.Column(db.Float, default=5, nullable=False)
    max_daily_loss_usdt = db.Column(db.Float, default=25, nullable=False)
    max_total_loss_usdt = db.Column(db.Float, default=100, nullable=False)
    max_open_positions = db.Column(db.Integer, default=1, nullable=False)
    cooldown_after_loss_seconds = db.Column(db.Integer, default=30, nullable=False)
    cooldown_after_win_seconds = db.Column(db.Integer, default=10, nullable=False)
    enabled = db.Column(db.Boolean, default=False, nullable=False)
    paper_mode_only = db.Column(db.Boolean, default=True, nullable=False)
    long_imbalance_threshold = db.Column(db.Float, default=1.3, nullable=False)
    short_imbalance_threshold = db.Column(db.Float, default=0.77, nullable=False)
    max_spread_percent = db.Column(db.Float, default=0.05, nullable=False)
    momentum_window_snapshots = db.Column(db.Integer, default=10, nullable=False)
    consensus_enabled = db.Column(db.Boolean, default=True, nullable=False)
    min_valid_exchanges = db.Column(db.Integer, default=2, nullable=False)
    min_confirming_exchanges = db.Column(db.Integer, default=2, nullable=False)
    min_consensus_ratio = db.Column(db.Float, default=0.6, nullable=False)
    max_snapshot_age_seconds = db.Column(db.Float, default=5, nullable=False)
    require_configured_exchange_signal = db.Column(db.Boolean, default=True, nullable=False)
    use_median_imbalance = db.Column(db.Boolean, default=True, nullable=False)
    imbalance_anomaly_min = db.Column(db.Float, default=0.1, nullable=False)
    imbalance_anomaly_max = db.Column(db.Float, default=10, nullable=False)
    exclude_anomalous_imbalance = db.Column(db.Boolean, default=True, nullable=False)
    cooldown_after_max_recovery_seconds = db.Column(db.Integer, default=600, nullable=False)
    feedback_enabled = db.Column(db.Boolean, default=True, nullable=False)
    feedback_lookback_trades = db.Column(db.Integer, default=50, nullable=False)
    side_loss_streak_limit = db.Column(db.Integer, default=3, nullable=False)
    side_cooldown_seconds = db.Column(db.Integer, default=600, nullable=False)
    min_side_win_rate = db.Column(db.Float, default=40, nullable=False)
    adaptive_consensus_boost = db.Column(db.Float, default=0.1, nullable=False)
    adaptive_min_valid_exchanges_boost = db.Column(db.Integer, default=1, nullable=False)
    paper_equity_usdt = db.Column(db.Float, default=10000, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class RecoveryState(Model, db.Model):
    __tablename__ = "recovery_state"

    strategy_config_id = db.Column(db.Integer, db.ForeignKey("order_book_pattern_strategy_config.id"), nullable=False)
    strategy_config = db.relationship("OrderBookPatternStrategyConfig")
    current_step = db.Column(db.Integer, default=0, nullable=False)
    current_margin = db.Column(db.Float, default=7, nullable=False)
    last_trade_result = db.Column(db.String(20), nullable=True)
    consecutive_losses = db.Column(db.Integer, default=0, nullable=False)
    is_stopped = db.Column(db.Boolean, default=False, nullable=False)
    stop_reason = db.Column(db.String(120), nullable=True)
    paused_until = db.Column(db.DateTime, nullable=True)
    last_closed_at = db.Column(db.DateTime, nullable=True)
    last_opened_at = db.Column(db.DateTime, nullable=True)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class StrategyRun(Model, db.Model):
    __tablename__ = "strategy_run"

    strategy_config_id = db.Column(db.Integer, db.ForeignKey("order_book_pattern_strategy_config.id"), nullable=False)
    strategy_config = db.relationship("OrderBookPatternStrategyConfig")
    status = db.Column(db.String(20), default="running", nullable=False)
    started_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    stopped_at = db.Column(db.DateTime, nullable=True)
    stop_reason = db.Column(db.String(120), nullable=True)


class StrategyRunTrade(Model, db.Model):
    __tablename__ = "strategy_run_trade"

    strategy_run_id = db.Column(db.Integer, db.ForeignKey("strategy_run.id"), nullable=True)
    strategy_config_id = db.Column(db.Integer, db.ForeignKey("order_book_pattern_strategy_config.id"), nullable=False)
    strategy_run = db.relationship("StrategyRun")
    strategy_config = db.relationship("OrderBookPatternStrategyConfig")
    exchange = db.Column(db.String(80), nullable=False)
    symbol = db.Column(db.String(40), nullable=False)
    side = db.Column(db.String(20), nullable=False)
    margin = db.Column(db.Float, nullable=False)
    leverage = db.Column(db.Float, nullable=False)
    notional = db.Column(db.Float, nullable=False)
    amount = db.Column(db.Float, nullable=False)
    entry_price = db.Column(db.Float, nullable=False)
    exit_price = db.Column(db.Float, nullable=True)
    pnl = db.Column(db.Float, default=0, nullable=False)
    result = db.Column(db.String(20), nullable=True)
    recovery_step = db.Column(db.Integer, default=0, nullable=False)
    reason_open = db.Column(db.String(255), nullable=True)
    reason_close = db.Column(db.String(80), nullable=True)
    opened_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    closed_at = db.Column(db.DateTime, nullable=True)
    is_archived = db.Column(db.Boolean, default=False, nullable=False)
    archived_at = db.Column(db.DateTime, nullable=True)
    archive_reason = db.Column(db.String(120), nullable=True)
    signal_consensus_direction = db.Column(db.String(20), nullable=True)
    signal_valid_exchanges_count = db.Column(db.Integer, nullable=True)
    signal_confirming_long_count = db.Column(db.Integer, nullable=True)
    signal_confirming_short_count = db.Column(db.Integer, nullable=True)
    signal_consensus_ratio_long = db.Column(db.Float, nullable=True)
    signal_consensus_ratio_short = db.Column(db.Float, nullable=True)
    signal_average_imbalance = db.Column(db.Float, nullable=True)
    signal_median_imbalance = db.Column(db.Float, nullable=True)
    signal_raw_average_imbalance = db.Column(db.Float, nullable=True)
    signal_anomalous_exchanges_count = db.Column(db.Integer, nullable=True)
    signal_excluded_anomalous_imbalance_exchanges_json = db.Column(db.Text, nullable=True)
    signal_average_momentum = db.Column(db.Float, nullable=True)
    signal_configured_exchange_imbalance = db.Column(db.Float, nullable=True)
    signal_configured_exchange_spread = db.Column(db.Float, nullable=True)
    signal_configured_exchange_momentum = db.Column(db.Float, nullable=True)
    signal_entry_blocked_reason = db.Column(db.String(120), nullable=True)
    signal_per_exchange_features_json = db.Column(db.Text, nullable=True)
    decision_snapshot_json = db.Column(db.Text, nullable=True)
    per_exchange_features_json = db.Column(db.Text, nullable=True)
    consensus_direction = db.Column(db.String(20), nullable=True)
    valid_exchanges_count = db.Column(db.Integer, nullable=True)
    confirming_long_count = db.Column(db.Integer, nullable=True)
    confirming_short_count = db.Column(db.Integer, nullable=True)
    consensus_ratio_long = db.Column(db.Float, nullable=True)
    consensus_ratio_short = db.Column(db.Float, nullable=True)
    average_imbalance = db.Column(db.Float, nullable=True)
    median_imbalance = db.Column(db.Float, nullable=True)
    raw_average_imbalance = db.Column(db.Float, nullable=True)
    anomalous_exchanges_count = db.Column(db.Integer, nullable=True)
    excluded_anomalous_imbalance_exchanges_json = db.Column(db.Text, nullable=True)
    average_momentum = db.Column(db.Float, nullable=True)
    configured_exchange_imbalance = db.Column(db.Float, nullable=True)
    configured_exchange_spread = db.Column(db.Float, nullable=True)
    configured_exchange_momentum = db.Column(db.Float, nullable=True)
    entry_reason = db.Column(db.String(255), nullable=True)
    holding_seconds = db.Column(db.Float, nullable=True)
