"""empty message

Revision ID: 20d9dcd922c4
Revises: 73df90677794
Create Date: 2025-05-24 10:52:34.191843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d9dcd922c4'
down_revision = '73df90677794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_pair', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_pair', schema=None) as batch_op:
        batch_op.drop_column('order_limit')

    # ### end Alembic commands ###
