"""empty message

Revision ID: 73df90677794
Revises: efcfc1c4d24c
Create Date: 2025-05-24 10:33:11.088482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73df90677794'
down_revision = 'efcfc1c4d24c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_path', sa.Text(), nullable=True))

    with op.batch_alter_table('trading_pair', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_path', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_pair', schema=None) as batch_op:
        batch_op.drop_column('icon_path')

    with op.batch_alter_table('exchange', schema=None) as batch_op:
        batch_op.drop_column('icon_path')

    # ### end Alembic commands ###
