"""empty message

Revision ID: 7768cdb70f8d
Revises: cd4b4e60fde0
Create Date: 2025-05-24 11:08:00.385114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7768cdb70f8d'
down_revision = 'cd4b4e60fde0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.Integer(), nullable=True))

    with op.batch_alter_table('trading_pair', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_pair', schema=None) as batch_op:
        batch_op.drop_column('index')

    with op.batch_alter_table('exchange', schema=None) as batch_op:
        batch_op.drop_column('index')

    # ### end Alembic commands ###
