"""empty message

Revision ID: a7e0d56d2e9b
Revises: d6aa1933ea3e
Create Date: 2025-05-26 23:53:41.203595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e0d56d2e9b'
down_revision = 'd6aa1933ea3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
