"""empty message

Revision ID: b29176601b9e
Revises: a7e0d56d2e9b
Create Date: 2025-05-30 10:13:42.630863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29176601b9e'
down_revision = 'a7e0d56d2e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade',
    sa.Column('timestamp', sa.String(length=80), nullable=False),
    sa.Column('price', sa.String(length=120), nullable=False),
    sa.Column('trading_pair_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trading_pair_id'], ['trading_pair.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade')
    # ### end Alembic commands ###
