"""empty message

Revision ID: cd4b4e60fde0
Revises: 20d9dcd922c4
Create Date: 2025-05-24 10:58:51.764331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4b4e60fde0'
down_revision = '20d9dcd922c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=True))

    with op.batch_alter_table('trading_pair', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_pair', schema=None) as batch_op:
        batch_op.drop_column('enabled')

    with op.batch_alter_table('exchange', schema=None) as batch_op:
        batch_op.drop_column('enabled')

    # ### end Alembic commands ###
