"""empty message

Revision ID: d6aa1933ea3e
Revises: e247296e76e8
Create Date: 2025-05-26 14:08:52.102569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6aa1933ea3e'
down_revision = 'e247296e76e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('api_secret', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange', schema=None) as batch_op:
        batch_op.drop_column('api_secret')
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
