"""empty message

Revision ID: e247296e76e8
Revises: 7768cdb70f8d
Create Date: 2025-05-25 10:22:39.955777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e247296e76e8'
down_revision = '7768cdb70f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_pair', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_purchase_price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_pair', schema=None) as batch_op:
        batch_op.drop_column('max_purchase_price')

    # ### end Alembic commands ###
